// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package project

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error)
	DeleteProject(ctx context.Context, projectID uuid.UUID) (uuid.UUID, error)
	GetProjectByID(ctx context.Context, projectID uuid.UUID) (GetProjectByIDRow, error)
	GetProjectIDByKey(ctx context.Context, projectKey string) (uuid.UUID, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error)
	LockActiveProject(ctx context.Context, projectID uuid.UUID) (uuid.UUID, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error)
}

var _ Querier = (*Queries)(nil)
