// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package project

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO onboarding.projects (name, project_key)
VALUES ($1, $2)
RETURNING id, name, project_key, created_at, updated_at
`

type CreateProjectParams struct {
	Name       string `json:"name"`
	ProjectKey string `json:"project_key"`
}

type CreateProjectRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	ProjectKey string             `json:"project_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Name, arg.ProjectKey)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
UPDATE onboarding.projects
SET deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id
`

func (q *Queries) DeleteProject(ctx context.Context, projectID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteProject, projectID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, project_key, created_at, updated_at
FROM onboarding.projects
WHERE id = $1
  AND deleted_at IS NULL
`

type GetProjectByIDRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	ProjectKey string             `json:"project_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetProjectByID(ctx context.Context, projectID uuid.UUID) (GetProjectByIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectByID, projectID)
	var i GetProjectByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectIDByKey = `-- name: GetProjectIDByKey :one
SELECT id
FROM onboarding.projects
WHERE project_key = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetProjectIDByKey(ctx context.Context, projectKey string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getProjectIDByKey, projectKey)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listProjects = `-- name: ListProjects :many
WITH filtered AS (
    SELECT id, name, project_key, created_at, updated_at
    FROM onboarding.projects
    WHERE deleted_at IS NULL
),
total AS (
    SELECT COUNT(*)::bigint AS value
    FROM filtered
),
page AS (
    SELECT id, name, project_key, created_at, updated_at
    FROM filtered
    ORDER BY created_at DESC, id DESC
    LIMIT $2::integer
    OFFSET $1::integer
)
SELECT page.id,
       page.name,
       page.project_key,
       page.created_at,
       page.updated_at,
       total.value AS total
FROM total
LEFT JOIN page ON TRUE
ORDER BY page.created_at DESC NULLS LAST, page.id DESC NULLS LAST
`

type ListProjectsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type ListProjectsRow struct {
	ID         pgtype.UUID        `json:"id"`
	Name       pgtype.Text        `json:"name"`
	ProjectKey pgtype.Text        `json:"project_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Total      int64              `json:"total"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProjectKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveProject = `-- name: LockActiveProject :one
SELECT id
FROM onboarding.projects
WHERE id = $1
  AND deleted_at IS NULL
    FOR SHARE
`

func (q *Queries) LockActiveProject(ctx context.Context, projectID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockActiveProject, projectID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE onboarding.projects
SET name = $1
WHERE id = $2
  AND deleted_at IS NULL
RETURNING id, name, project_key, created_at, updated_at
`

type UpdateProjectParams struct {
	Name      string    `json:"name"`
	ProjectID uuid.UUID `json:"project_id"`
}

type UpdateProjectRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	ProjectKey string             `json:"project_key"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.Name, arg.ProjectID)
	var i UpdateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
