// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package scenario

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type OnboardingScenarioTestToken struct {
	ID         uuid.UUID          `json:"id"`
	ScenarioID uuid.UUID          `json:"scenario_id"`
	Hash       []byte             `json:"hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}
