// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package scenario

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScenarioTestToken = `-- name: CreateScenarioTestToken :one
INSERT INTO onboarding.scenario_test_tokens (
    scenario_id,
    hash,
    expires_at
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, scenario_id, hash, created_at, expires_at
`

type CreateScenarioTestTokenParams struct {
	ScenarioID uuid.UUID          `json:"scenario_id"`
	Hash       []byte             `json:"hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateScenarioTestToken(ctx context.Context, arg CreateScenarioTestTokenParams) (OnboardingScenarioTestToken, error) {
	row := q.db.QueryRow(ctx, createScenarioTestToken, arg.ScenarioID, arg.Hash, arg.ExpiresAt)
	var i OnboardingScenarioTestToken
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.Hash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
