// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package scenario

import (
	"context"
)

type Querier interface {
	CreateScenarioTestToken(ctx context.Context, arg CreateScenarioTestTokenParams) (OnboardingScenarioTestToken, error)
}

var _ Querier = (*Queries)(nil)
