// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package scenario

import (
	"database/sql/driver"
	"fmt"
)

type OnboardingScenarioStatus string

const (
	OnboardingScenarioStatusEnabled       OnboardingScenarioStatus = "enabled"
	OnboardingScenarioStatusDisabled      OnboardingScenarioStatus = "disabled"
	OnboardingScenarioStatusInDevelopment OnboardingScenarioStatus = "in_development"
)

func (e *OnboardingScenarioStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OnboardingScenarioStatus(s)
	case string:
		*e = OnboardingScenarioStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OnboardingScenarioStatus: %T", src)
	}
	return nil
}

type NullOnboardingScenarioStatus struct {
	OnboardingScenarioStatus OnboardingScenarioStatus `json:"onboarding_scenario_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if OnboardingScenarioStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOnboardingScenarioStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OnboardingScenarioStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OnboardingScenarioStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOnboardingScenarioStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OnboardingScenarioStatus), nil
}
