// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package scenario

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScenario = `-- name: CreateScenario :one
INSERT INTO onboarding.scenarios (
    project_id,
    name,
    description,
    page_pattern
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id,
          project_id,
          name,
          description,
          page_pattern,
          status,
          published_at,
          created_at,
          updated_at
`

type CreateScenarioParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	PagePattern string    `json:"page_pattern"`
}

type CreateScenarioRow struct {
	ID          uuid.UUID                `json:"id"`
	ProjectID   uuid.UUID                `json:"project_id"`
	Name        string                   `json:"name"`
	Description string                   `json:"description"`
	PagePattern string                   `json:"page_pattern"`
	Status      OnboardingScenarioStatus `json:"status"`
	PublishedAt pgtype.Timestamptz       `json:"published_at"`
	CreatedAt   pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz       `json:"updated_at"`
}

func (q *Queries) CreateScenario(ctx context.Context, arg CreateScenarioParams) (CreateScenarioRow, error) {
	row := q.db.QueryRow(ctx, createScenario,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.PagePattern,
	)
	var i CreateScenarioRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.PagePattern,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScenario = `-- name: DeleteScenario :one
UPDATE onboarding.scenarios AS s
SET deleted_at = NOW()
FROM onboarding.projects AS p
WHERE s.id = $1
  AND p.id = s.project_id
  AND s.deleted_at IS NULL
  AND p.deleted_at IS NULL
RETURNING s.id
`

func (q *Queries) DeleteScenario(ctx context.Context, scenarioID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteScenario, scenarioID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const disableScenario = `-- name: DisableScenario :one
UPDATE onboarding.scenarios
SET status = 'disabled'
WHERE id = $1
  AND status = 'enabled'
  AND deleted_at IS NULL
RETURNING id,
          project_id,
          name,
          description,
          page_pattern,
          status,
          published_at,
          created_at,
          updated_at
`

type DisableScenarioRow struct {
	ID          uuid.UUID                `json:"id"`
	ProjectID   uuid.UUID                `json:"project_id"`
	Name        string                   `json:"name"`
	Description string                   `json:"description"`
	PagePattern string                   `json:"page_pattern"`
	Status      OnboardingScenarioStatus `json:"status"`
	PublishedAt pgtype.Timestamptz       `json:"published_at"`
	CreatedAt   pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz       `json:"updated_at"`
}

func (q *Queries) DisableScenario(ctx context.Context, scenarioID uuid.UUID) (DisableScenarioRow, error) {
	row := q.db.QueryRow(ctx, disableScenario, scenarioID)
	var i DisableScenarioRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.PagePattern,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enableScenario = `-- name: EnableScenario :one
UPDATE onboarding.scenarios
SET status = 'enabled'
WHERE id = $1
  AND status = 'disabled'
  AND deleted_at IS NULL
RETURNING id,
          project_id,
          name,
          description,
          page_pattern,
          status,
          published_at,
          created_at,
          updated_at
`

type EnableScenarioRow struct {
	ID          uuid.UUID                `json:"id"`
	ProjectID   uuid.UUID                `json:"project_id"`
	Name        string                   `json:"name"`
	Description string                   `json:"description"`
	PagePattern string                   `json:"page_pattern"`
	Status      OnboardingScenarioStatus `json:"status"`
	PublishedAt pgtype.Timestamptz       `json:"published_at"`
	CreatedAt   pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz       `json:"updated_at"`
}

func (q *Queries) EnableScenario(ctx context.Context, scenarioID uuid.UUID) (EnableScenarioRow, error) {
	row := q.db.QueryRow(ctx, enableScenario, scenarioID)
	var i EnableScenarioRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.PagePattern,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScenarioByID = `-- name: GetScenarioByID :one
SELECT s.id,
       s.project_id,
       s.name,
       s.description,
       s.page_pattern,
       s.status,
       s.published_at,
       s.created_at,
       s.updated_at
FROM onboarding.scenarios AS s
JOIN onboarding.projects AS p ON p.id = s.project_id
WHERE s.id = $1
  AND s.deleted_at IS NULL
  AND p.deleted_at IS NULL
`

type GetScenarioByIDRow struct {
	ID          uuid.UUID                `json:"id"`
	ProjectID   uuid.UUID                `json:"project_id"`
	Name        string                   `json:"name"`
	Description string                   `json:"description"`
	PagePattern string                   `json:"page_pattern"`
	Status      OnboardingScenarioStatus `json:"status"`
	PublishedAt pgtype.Timestamptz       `json:"published_at"`
	CreatedAt   pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz       `json:"updated_at"`
}

func (q *Queries) GetScenarioByID(ctx context.Context, scenarioID uuid.UUID) (GetScenarioByIDRow, error) {
	row := q.db.QueryRow(ctx, getScenarioByID, scenarioID)
	var i GetScenarioByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.PagePattern,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScenariosByProjectID = `-- name: ListScenariosByProjectID :many
WITH filtered AS (
    SELECT s.id,
           s.project_id,
           s.name,
           s.description,
           s.page_pattern,
           s.status,
           s.published_at,
           s.created_at,
           s.updated_at,
           (
               SELECT COUNT(*)::bigint
               FROM onboarding.steps AS st
               WHERE st.scenario_id = s.id
                 AND st.deleted_at IS NULL
           ) AS steps_count
    FROM onboarding.scenarios AS s
    WHERE s.project_id = $1
      AND s.deleted_at IS NULL
      AND (
          $2::text IS NULL
          OR s.status::text = $2::text
      )
),
total AS (
    SELECT COUNT(*)::bigint AS value
    FROM filtered
),
page AS (
    SELECT id, project_id, name, description, page_pattern, status, published_at, created_at, updated_at, steps_count
    FROM filtered
    ORDER BY created_at DESC, id DESC
    LIMIT $4::integer
    OFFSET $3::integer
)
SELECT page.id,
       page.project_id,
       page.name,
       page.description,
       page.page_pattern,
       page.status,
       page.published_at,
       page.created_at,
       page.updated_at,
       page.steps_count,
       total.value AS total
FROM total
LEFT JOIN page ON TRUE
ORDER BY page.created_at DESC NULLS LAST, page.id DESC NULLS LAST
`

type ListScenariosByProjectIDParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	Status     pgtype.Text `json:"status"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListScenariosByProjectIDRow struct {
	ID          pgtype.UUID                  `json:"id"`
	ProjectID   pgtype.UUID                  `json:"project_id"`
	Name        pgtype.Text                  `json:"name"`
	Description pgtype.Text                  `json:"description"`
	PagePattern pgtype.Text                  `json:"page_pattern"`
	Status      NullOnboardingScenarioStatus `json:"status"`
	PublishedAt pgtype.Timestamptz           `json:"published_at"`
	CreatedAt   pgtype.Timestamptz           `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz           `json:"updated_at"`
	StepsCount  pgtype.Int8                  `json:"steps_count"`
	Total       int64                        `json:"total"`
}

func (q *Queries) ListScenariosByProjectID(ctx context.Context, arg ListScenariosByProjectIDParams) ([]ListScenariosByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, listScenariosByProjectID,
		arg.ProjectID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScenariosByProjectIDRow
	for rows.Next() {
		var i ListScenariosByProjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.PagePattern,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StepsCount,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveScenario = `-- name: LockActiveScenario :one
SELECT s.id,
       s.project_id,
       s.name,
       s.description,
       s.page_pattern,
       s.status,
       s.published_at,
       s.created_at,
       s.updated_at
FROM onboarding.scenarios AS s
JOIN onboarding.projects AS p ON p.id = s.project_id
WHERE s.id = $1
  AND s.deleted_at IS NULL
  AND p.deleted_at IS NULL
FOR UPDATE OF s
FOR SHARE OF p
`

type LockActiveScenarioRow struct {
	ID          uuid.UUID                `json:"id"`
	ProjectID   uuid.UUID                `json:"project_id"`
	Name        string                   `json:"name"`
	Description string                   `json:"description"`
	PagePattern string                   `json:"page_pattern"`
	Status      OnboardingScenarioStatus `json:"status"`
	PublishedAt pgtype.Timestamptz       `json:"published_at"`
	CreatedAt   pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz       `json:"updated_at"`
}

func (q *Queries) LockActiveScenario(ctx context.Context, scenarioID uuid.UUID) (LockActiveScenarioRow, error) {
	row := q.db.QueryRow(ctx, lockActiveScenario, scenarioID)
	var i LockActiveScenarioRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.PagePattern,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const publishScenario = `-- name: PublishScenario :one
UPDATE onboarding.scenarios
SET status       = 'enabled',
    published_at = COALESCE(published_at, NOW())
WHERE id = $1
  AND status = 'in_development'
  AND deleted_at IS NULL
RETURNING id,
          project_id,
          name,
          description,
          page_pattern,
          status,
          published_at,
          created_at,
          updated_at
`

type PublishScenarioRow struct {
	ID          uuid.UUID                `json:"id"`
	ProjectID   uuid.UUID                `json:"project_id"`
	Name        string                   `json:"name"`
	Description string                   `json:"description"`
	PagePattern string                   `json:"page_pattern"`
	Status      OnboardingScenarioStatus `json:"status"`
	PublishedAt pgtype.Timestamptz       `json:"published_at"`
	CreatedAt   pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz       `json:"updated_at"`
}

func (q *Queries) PublishScenario(ctx context.Context, scenarioID uuid.UUID) (PublishScenarioRow, error) {
	row := q.db.QueryRow(ctx, publishScenario, scenarioID)
	var i PublishScenarioRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.PagePattern,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScenario = `-- name: UpdateScenario :one
UPDATE onboarding.scenarios
SET name         = COALESCE($1, name),
    description  = COALESCE($2, description),
    page_pattern = COALESCE($3, page_pattern)
WHERE id = $4
  AND deleted_at IS NULL
RETURNING id,
          project_id,
          name,
          description,
          page_pattern,
          status,
          published_at,
          created_at,
          updated_at
`

type UpdateScenarioParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	PagePattern pgtype.Text `json:"page_pattern"`
	ScenarioID  uuid.UUID   `json:"scenario_id"`
}

type UpdateScenarioRow struct {
	ID          uuid.UUID                `json:"id"`
	ProjectID   uuid.UUID                `json:"project_id"`
	Name        string                   `json:"name"`
	Description string                   `json:"description"`
	PagePattern string                   `json:"page_pattern"`
	Status      OnboardingScenarioStatus `json:"status"`
	PublishedAt pgtype.Timestamptz       `json:"published_at"`
	CreatedAt   pgtype.Timestamptz       `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz       `json:"updated_at"`
}

func (q *Queries) UpdateScenario(ctx context.Context, arg UpdateScenarioParams) (UpdateScenarioRow, error) {
	row := q.db.QueryRow(ctx, updateScenario,
		arg.Name,
		arg.Description,
		arg.PagePattern,
		arg.ScenarioID,
	)
	var i UpdateScenarioRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.PagePattern,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
