// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package scenario

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateScenario(ctx context.Context, arg CreateScenarioParams) (CreateScenarioRow, error)
	DeleteScenario(ctx context.Context, scenarioID uuid.UUID) (uuid.UUID, error)
	DisableScenario(ctx context.Context, scenarioID uuid.UUID) (DisableScenarioRow, error)
	EnableScenario(ctx context.Context, scenarioID uuid.UUID) (EnableScenarioRow, error)
	GetScenarioByID(ctx context.Context, scenarioID uuid.UUID) (GetScenarioByIDRow, error)
	ListScenariosByProjectID(ctx context.Context, arg ListScenariosByProjectIDParams) ([]ListScenariosByProjectIDRow, error)
	LockActiveScenario(ctx context.Context, scenarioID uuid.UUID) (LockActiveScenarioRow, error)
	PublishScenario(ctx context.Context, scenarioID uuid.UUID) (PublishScenarioRow, error)
	UpdateScenario(ctx context.Context, arg UpdateScenarioParams) (UpdateScenarioRow, error)
}

var _ Querier = (*Queries)(nil)
