// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package scenario

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applyStepOrder = `-- name: ApplyStepOrder :execrows
WITH requested_order AS (
    SELECT input.step_id,
           input.ordinality::integer AS step_num
    FROM unnest($2::uuid[])
             WITH ORDINALITY AS input(step_id, ordinality)
)
UPDATE onboarding.steps AS s
SET step_num = requested_order.step_num
FROM requested_order
WHERE s.scenario_id = $1
  AND s.id = requested_order.step_id
  AND s.deleted_at IS NULL
`

type ApplyStepOrderParams struct {
	ScenarioID     uuid.UUID   `json:"scenario_id"`
	OrderedStepIds []uuid.UUID `json:"ordered_step_ids"`
}

func (q *Queries) ApplyStepOrder(ctx context.Context, arg ApplyStepOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, applyStepOrder, arg.ScenarioID, arg.OrderedStepIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createStep = `-- name: CreateStep :one
INSERT INTO onboarding.steps (
    scenario_id,
    element_id,
    step_num,
    title,
    description,
    frontend_data
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id,
          scenario_id,
          element_id,
          step_num,
          title,
          description,
          frontend_data,
          created_at,
          updated_at
`

type CreateStepParams struct {
	ScenarioID   uuid.UUID `json:"scenario_id"`
	ElementID    uuid.UUID `json:"element_id"`
	StepNum      int32     `json:"step_num"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	FrontendData []byte    `json:"frontend_data"`
}

type CreateStepRow struct {
	ID           uuid.UUID          `json:"id"`
	ScenarioID   uuid.UUID          `json:"scenario_id"`
	ElementID    uuid.UUID          `json:"element_id"`
	StepNum      int32              `json:"step_num"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	FrontendData []byte             `json:"frontend_data"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) (CreateStepRow, error) {
	row := q.db.QueryRow(ctx, createStep,
		arg.ScenarioID,
		arg.ElementID,
		arg.StepNum,
		arg.Title,
		arg.Description,
		arg.FrontendData,
	)
	var i CreateStepRow
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.ElementID,
		&i.StepNum,
		&i.Title,
		&i.Description,
		&i.FrontendData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStep = `-- name: DeleteStep :one
UPDATE onboarding.steps
SET deleted_at = NOW()
WHERE scenario_id = $1
  AND id = $2
  AND deleted_at IS NULL
    RETURNING id, step_num
`

type DeleteStepParams struct {
	ScenarioID uuid.UUID `json:"scenario_id"`
	StepID     uuid.UUID `json:"step_id"`
}

type DeleteStepRow struct {
	ID      uuid.UUID `json:"id"`
	StepNum int32     `json:"step_num"`
}

func (q *Queries) DeleteStep(ctx context.Context, arg DeleteStepParams) (DeleteStepRow, error) {
	row := q.db.QueryRow(ctx, deleteStep, arg.ScenarioID, arg.StepID)
	var i DeleteStepRow
	err := row.Scan(&i.ID, &i.StepNum)
	return i, err
}

const getMaxStepNumber = `-- name: GetMaxStepNumber :one
SELECT COALESCE(MAX(step_num), 0)::integer AS max_step_number
FROM onboarding.steps
WHERE scenario_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetMaxStepNumber(ctx context.Context, scenarioID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxStepNumber, scenarioID)
	var max_step_number int32
	err := row.Scan(&max_step_number)
	return max_step_number, err
}

const getStepByID = `-- name: GetStepByID :one
SELECT id,
       scenario_id,
       element_id,
       step_num,
       title,
       description,
       frontend_data,
       created_at,
       updated_at
FROM onboarding.steps
WHERE scenario_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetStepByIDParams struct {
	ScenarioID uuid.UUID `json:"scenario_id"`
	StepID     uuid.UUID `json:"step_id"`
}

type GetStepByIDRow struct {
	ID           uuid.UUID          `json:"id"`
	ScenarioID   uuid.UUID          `json:"scenario_id"`
	ElementID    uuid.UUID          `json:"element_id"`
	StepNum      int32              `json:"step_num"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	FrontendData []byte             `json:"frontend_data"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetStepByID(ctx context.Context, arg GetStepByIDParams) (GetStepByIDRow, error) {
	row := q.db.QueryRow(ctx, getStepByID, arg.ScenarioID, arg.StepID)
	var i GetStepByIDRow
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.ElementID,
		&i.StepNum,
		&i.Title,
		&i.Description,
		&i.FrontendData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isElementUsedBySteps = `-- name: IsElementUsedBySteps :one
SELECT EXISTS (
    SELECT 1
    FROM onboarding.steps AS st
    JOIN onboarding.scenarios AS s ON s.id = st.scenario_id
    WHERE st.element_id = $1
      AND st.deleted_at IS NULL
      AND s.deleted_at IS NULL
) AS is_used
`

func (q *Queries) IsElementUsedBySteps(ctx context.Context, elementID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isElementUsedBySteps, elementID)
	var is_used bool
	err := row.Scan(&is_used)
	return is_used, err
}

const listStepsByScenarioID = `-- name: ListStepsByScenarioID :many
SELECT id,
       scenario_id,
       element_id,
       step_num,
       title,
       description,
       frontend_data,
       created_at,
       updated_at
FROM onboarding.steps
WHERE scenario_id = $1
  AND deleted_at IS NULL
ORDER BY step_num, id
`

type ListStepsByScenarioIDRow struct {
	ID           uuid.UUID          `json:"id"`
	ScenarioID   uuid.UUID          `json:"scenario_id"`
	ElementID    uuid.UUID          `json:"element_id"`
	StepNum      int32              `json:"step_num"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	FrontendData []byte             `json:"frontend_data"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListStepsByScenarioID(ctx context.Context, scenarioID uuid.UUID) ([]ListStepsByScenarioIDRow, error) {
	rows, err := q.db.Query(ctx, listStepsByScenarioID, scenarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStepsByScenarioIDRow
	for rows.Next() {
		var i ListStepsByScenarioIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ScenarioID,
			&i.ElementID,
			&i.StepNum,
			&i.Title,
			&i.Description,
			&i.FrontendData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveStep = `-- name: LockActiveStep :one
SELECT id,
       scenario_id,
       element_id,
       step_num,
       title,
       description,
       frontend_data,
       created_at,
       updated_at
FROM onboarding.steps
WHERE scenario_id = $1
  AND id = $2
  AND deleted_at IS NULL
FOR UPDATE
`

type LockActiveStepParams struct {
	ScenarioID uuid.UUID `json:"scenario_id"`
	StepID     uuid.UUID `json:"step_id"`
}

type LockActiveStepRow struct {
	ID           uuid.UUID          `json:"id"`
	ScenarioID   uuid.UUID          `json:"scenario_id"`
	ElementID    uuid.UUID          `json:"element_id"`
	StepNum      int32              `json:"step_num"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	FrontendData []byte             `json:"frontend_data"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) LockActiveStep(ctx context.Context, arg LockActiveStepParams) (LockActiveStepRow, error) {
	row := q.db.QueryRow(ctx, lockActiveStep, arg.ScenarioID, arg.StepID)
	var i LockActiveStepRow
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.ElementID,
		&i.StepNum,
		&i.Title,
		&i.Description,
		&i.FrontendData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockActiveStepsByScenarioID = `-- name: LockActiveStepsByScenarioID :many
SELECT id, step_num
FROM onboarding.steps
WHERE scenario_id = $1
  AND deleted_at IS NULL
ORDER BY step_num, id
FOR UPDATE
`

type LockActiveStepsByScenarioIDRow struct {
	ID      uuid.UUID `json:"id"`
	StepNum int32     `json:"step_num"`
}

func (q *Queries) LockActiveStepsByScenarioID(ctx context.Context, scenarioID uuid.UUID) ([]LockActiveStepsByScenarioIDRow, error) {
	rows, err := q.db.Query(ctx, lockActiveStepsByScenarioID, scenarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockActiveStepsByScenarioIDRow
	for rows.Next() {
		var i LockActiveStepsByScenarioIDRow
		if err := rows.Scan(&i.ID, &i.StepNum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveStepsOutOfOrderRange = `-- name: MoveStepsOutOfOrderRange :exec
WITH current_range AS (
    SELECT COALESCE(MAX(step_num), 0)::integer AS offset
    FROM onboarding.steps
    WHERE scenario_id = $1
      AND deleted_at IS NULL
)
UPDATE onboarding.steps AS s
SET step_num = s.step_num + current_range.offset
FROM current_range
WHERE s.scenario_id = $1
  AND s.deleted_at IS NULL
  AND current_range.offset > 0
`

func (q *Queries) MoveStepsOutOfOrderRange(ctx context.Context, scenarioID uuid.UUID) error {
	_, err := q.db.Exec(ctx, moveStepsOutOfOrderRange, scenarioID)
	return err
}

const updateStep = `-- name: UpdateStep :one
UPDATE onboarding.steps
SET element_id    = COALESCE($1, element_id),
    title         = COALESCE($2, title),
    description   = COALESCE($3, description),
    frontend_data = COALESCE($4, frontend_data)
WHERE scenario_id = $5
  AND id = $6
  AND deleted_at IS NULL
    RETURNING id,
          scenario_id,
          element_id,
          step_num,
          title,
          description,
          frontend_data,
          created_at,
          updated_at
`

type UpdateStepParams struct {
	ElementID    pgtype.UUID `json:"element_id"`
	Title        pgtype.Text `json:"title"`
	Description  pgtype.Text `json:"description"`
	FrontendData []byte      `json:"frontend_data"`
	ScenarioID   uuid.UUID   `json:"scenario_id"`
	StepID       uuid.UUID   `json:"step_id"`
}

type UpdateStepRow struct {
	ID           uuid.UUID          `json:"id"`
	ScenarioID   uuid.UUID          `json:"scenario_id"`
	ElementID    uuid.UUID          `json:"element_id"`
	StepNum      int32              `json:"step_num"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	FrontendData []byte             `json:"frontend_data"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateStep(ctx context.Context, arg UpdateStepParams) (UpdateStepRow, error) {
	row := q.db.QueryRow(ctx, updateStep,
		arg.ElementID,
		arg.Title,
		arg.Description,
		arg.FrontendData,
		arg.ScenarioID,
		arg.StepID,
	)
	var i UpdateStepRow
	err := row.Scan(
		&i.ID,
		&i.ScenarioID,
		&i.ElementID,
		&i.StepNum,
		&i.Title,
		&i.Description,
		&i.FrontendData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
