// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package scenario

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ApplyStepOrder(ctx context.Context, arg ApplyStepOrderParams) (int64, error)
	CreateStep(ctx context.Context, arg CreateStepParams) (CreateStepRow, error)
	DeleteStep(ctx context.Context, arg DeleteStepParams) (DeleteStepRow, error)
	GetMaxStepNumber(ctx context.Context, scenarioID uuid.UUID) (int32, error)
	GetStepByID(ctx context.Context, arg GetStepByIDParams) (GetStepByIDRow, error)
	IsElementUsedBySteps(ctx context.Context, elementID uuid.UUID) (bool, error)
	ListStepsByScenarioID(ctx context.Context, scenarioID uuid.UUID) ([]ListStepsByScenarioIDRow, error)
	LockActiveStep(ctx context.Context, arg LockActiveStepParams) (LockActiveStepRow, error)
	LockActiveStepsByScenarioID(ctx context.Context, scenarioID uuid.UUID) ([]LockActiveStepsByScenarioIDRow, error)
	MoveStepsOutOfOrderRange(ctx context.Context, scenarioID uuid.UUID) error
	UpdateStep(ctx context.Context, arg UpdateStepParams) (UpdateStepRow, error)
}

var _ Querier = (*Queries)(nil)
