// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package element

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateElement(ctx context.Context, arg CreateElementParams) (CreateElementRow, error)
	DeleteElement(ctx context.Context, arg DeleteElementParams) (uuid.UUID, error)
	ListElementsByProjectID(ctx context.Context, arg ListElementsByProjectIDParams) ([]ListElementsByProjectIDRow, error)
	ListPagesByProjectID(ctx context.Context, projectID uuid.UUID) ([]string, error)
	LockActiveElement(ctx context.Context, arg LockActiveElementParams) (uuid.UUID, error)
	UpdateElement(ctx context.Context, arg UpdateElementParams) (UpdateElementRow, error)
}

var _ Querier = (*Queries)(nil)
