// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package element

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createElement = `-- name: CreateElement :one
INSERT INTO onboarding.elements (project_id, key, label, description)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, key, label, description, created_at, updated_at
`

type CreateElementParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Key         string    `json:"key"`
	Label       string    `json:"label"`
	Description string    `json:"description"`
}

type CreateElementRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Key         string             `json:"key"`
	Label       string             `json:"label"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateElement(ctx context.Context, arg CreateElementParams) (CreateElementRow, error) {
	row := q.db.QueryRow(ctx, createElement,
		arg.ProjectID,
		arg.Key,
		arg.Label,
		arg.Description,
	)
	var i CreateElementRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteElement = `-- name: DeleteElement :one
UPDATE onboarding.elements
SET deleted_at = NOW()
WHERE project_id = $1
  AND id = $2
  AND deleted_at IS NULL
RETURNING id
`

type DeleteElementParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	ElementID uuid.UUID `json:"element_id"`
}

func (q *Queries) DeleteElement(ctx context.Context, arg DeleteElementParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteElement, arg.ProjectID, arg.ElementID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listElementsByProjectID = `-- name: ListElementsByProjectID :many
SELECT id, project_id, key, label, description, created_at, updated_at
FROM onboarding.elements
WHERE project_id = $1
  AND deleted_at IS NULL
ORDER BY created_at, id
`

type ListElementsByProjectIDRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Key         string             `json:"key"`
	Label       string             `json:"label"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListElementsByProjectID(ctx context.Context, projectID uuid.UUID) ([]ListElementsByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, listElementsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListElementsByProjectIDRow
	for rows.Next() {
		var i ListElementsByProjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Label,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveElement = `-- name: LockActiveElement :one
SELECT id
FROM onboarding.elements
WHERE id = $1
  AND project_id = $2
  AND deleted_at IS NULL
    FOR UPDATE
`

type LockActiveElementParams struct {
	ElementID uuid.UUID `json:"element_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) LockActiveElement(ctx context.Context, arg LockActiveElementParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockActiveElement, arg.ElementID, arg.ProjectID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateElement = `-- name: UpdateElement :one
UPDATE onboarding.elements
SET key         = COALESCE($1, key),
    label       = COALESCE($2, label),
    description = COALESCE($3, description)
WHERE project_id = $4
  AND id = $5
  AND deleted_at IS NULL
RETURNING id, project_id, key, label, description, created_at, updated_at
`

type UpdateElementParams struct {
	Key         pgtype.Text `json:"key"`
	Label       pgtype.Text `json:"label"`
	Description pgtype.Text `json:"description"`
	ProjectID   uuid.UUID   `json:"project_id"`
	ElementID   uuid.UUID   `json:"element_id"`
}

type UpdateElementRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Key         string             `json:"key"`
	Label       string             `json:"label"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateElement(ctx context.Context, arg UpdateElementParams) (UpdateElementRow, error) {
	row := q.db.QueryRow(ctx, updateElement,
		arg.Key,
		arg.Label,
		arg.Description,
		arg.ProjectID,
		arg.ElementID,
	)
	var i UpdateElementRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Label,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
